question_data = [{"type": "boolean", "difficulty": "medium", "category": "History",
                                                  "question": "&quot;I disapprove of what you say, but I will defend to the death your right to say it&quot; is a quote from French philosopher Voltaire.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "hard",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "In &quot;Call Of Duty: World At War&quot;, the first appearance of the &quot;PPSH-41&quot; in &quot;Zombies&quot; was in the map &quot;Der Riese&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "General Knowledge",
                                                  "question": "When you cry in space, your tears stick to your face.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Film",
                                                  "question": "Leonardo DiCaprio won an Oscar for Best Actor in 2004&#039;s &quot;The Aviator&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "In the game &quot;Subnautica&quot;, a &quot;Cave Crawler&quot; will attack you.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Science: Computers",
                                                  "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy", "category": "Politics",
                                                  "question": "In 2016, the United Kingdom voted to stay in the EU.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "General Knowledge",
                                                  "question": "The French word for &quot;glass&quot; is &quot;glace&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "Rollercoaster Tycoon 1 and 2 were developed by Chris Sawyer.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "The ghosts in &quot;Pac-Man&quot; and &quot;Ms. Pac-Man&quot; have completely different behavior.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "General Knowledge",
                                                  "question": "The mitochondria is the powerhouse of the cell.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Science: Mathematics", "question": "E = MC3",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "medium", "category": "History",
                                                  "question": "Augustus was the cousin of Julius Caesar. ",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "Gordon Freeman, the protagonist of &quot;Half-Life&quot;, is said to have once had a ponytail.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "The Fiat Multipla is a drivable car in &quot;Forza Horizon 3&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Entertainment: Music",
                                                  "question": "The country song  &ldquo;A Boy Named Sue&rdquo; was written by Shel Silverstein.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy", "category": "Politics",
                                                  "question": "One of Barack Obama&#039;s United States presidential campaign slogan&#039;s was &quot;Yes We Can&quot;.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "General Knowledge",
                                                  "question": "The French word to travel is &quot;Travail&quot;",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "In &quot;Team Fortress 2&quot;, the &quot;Bill&#039;s Hat&quot; is a reference to the game &quot;Dota 2&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "In RuneScape, one must complete the &quot;Dragon Slayer&quot; quest before equipping Rune Platelegs.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Science &amp; Nature",
                                                  "question": "In the periodic table, Potassium&#039;s symbol is the letter K.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "General Knowledge",
                                                  "question": "French is an official language in Canada.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Science: Computers",
                                                  "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "The scrapped Sonic the Hedgehog 2 level &quot;Hidden Palace Zone&quot; was later reused in the iOS port of the game. ",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "In World of Warcraft lore, Thrall is the original wielder of &quot;Doomhammer&quot;.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Entertainment: Video Games",
                                                  "question": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "easy", "category": "Animals",
                                                  "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"type": "boolean", "difficulty": "easy",
                                                  "category": "Science &amp; Nature",
                                                  "question": "The shape of the Earth is a perfect sphere.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "medium",
                                                  "category": "Entertainment: Television",
                                                  "question": "The show &quot;Gilligan&#039;s Island&quot; was cancelled because of low ratings.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"type": "boolean", "difficulty": "hard",
                                                  "category": "Science &amp; Nature",
                                                  "question": "The chemical element Lithium is named after the country of Lithuania.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]}]
